version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.d2cp.io`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=httpchallenge"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik
      - grafana
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafanaprom.rule=Host(`prometheus.grafana.d2cp.io`)"
      - "traefik.http.routers.grafanaprom.entrypoints=websecure"
      - "traefik.http.routers.grafanaprom.tls.certresolver=httpchallenge"
      - "traefik.http.services.grafanaprom.loadbalancer.server.port=9090"
    networks:
      - traefik
      - grafana

volumes:
  grafana-storage:
  prometheus_storage:


networks:
  traefik:
    external: true
  grafana:
